# Generated by Django 3.2.8 on 2021-11-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211108_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
